fix: auto detect gaslimit on withdraw
ScopeLift/umbra-protocol pull request #285
Opened 2022-01-28 01:52 UTC by thelostone-mc

#### Description 

`withdrawal` function has been updated and when invoked
-  if `overrides.gasLimit` is passed ->  that value is used
-  else it will try to fetch the gasLimit via `estimateGas`
- and if any error occurs -> will default to `2100` 

#### Refs 

fixes : https://github.com/ScopeLift/umbra-protocol/issues/262

#### Testing 

Pending test locally

2022-01-28 15:50 UTC, mds1 commented on umbra-js/src/classes/Umbra.ts
> +      // Estimate gas limit if not provided
One thing we also want to add is a check, probably during setup of `AccountReceiveTableWithdrawConfirmation.vue`, that runs the same `estimateGas` call and updates the fee amount show to the user. Currently if I withdraw to e.g. [0x6851D6fDFAfD08c0295C392436245E5bc78B0185](https://rinkeby.etherscan.io/address/0x6851d6fdfafd08c0295c392436245e5bc78b0185#code), which is a random gnosis safe I found on rinkeby, then the send method here correctly uses the right gas limit, but the estimated fee shown to the user is incorrect.

My suggestion would be to keep the current logic in this file as a fallback, but our frontend should also call `estimateGas`, show the appropriate fee, and pass in the gas limit override to this `withdraw` method

<img src="https://user-images.githubusercontent.com/17163988/151577109-50c2ce7f-a456-456c-ae65-8f91cab4b128.png" width=400 />

2022-01-31 15:48 UTC, mds1 reviewed
lgtm once conflict is resolved. I don't have permission to push to your branch (there should be a checkbox in the PR you can enable), but the conflict fix should be this:

```typescript
const gasPrice = network.value?.chainId === 1 ? await tryGetGasPrice() : await provider.value?.getGasPrice(); // use blocknative on mainnet, the node elsewhere
const ethFee = gasLimit.value.mul(gasPrice as BigNumber);
```

after conflict fix + @apbendi QA testing we can merge!

2022-02-03 12:13 UTC, thelostone-mc commented
@mds1 doneeee

2022-02-03 22:34 UTC, apbendi requested changes
Hey @thelostone-mc, thanks for the contribution! The core fix seems to be working, however, when I test a withdrawal on Polygon using ENS, I get the following error when it attempts to estimate gas:

<img width="722" alt="Screen Shot 2022-02-03 at 5 33 31 PM" src="https://user-images.githubusercontent.com/1479802/152440503-dbffccef-cd84-4c23-bb97-e6bcafee9346.png">

This error does not occur with the currently deployed version.

2022-02-03 23:40 UTC, mds1 commented
@apbendi When exactly are you seeing that? I tried to reproduce but using `msolomon.eth` as the recipient works for me on polygon locally—I was able to get to the MM confirmation then rejected the transaction. Maybe try re-installing packages as a sanity check? (though the version number there looks correct...)

2022-02-04 14:35 UTC, apbendi commented
@mds1 I did fresh install to be sure and I'm still seeing the issue. See below:

![umbra-polygon-ens-fail](https://user-images.githubusercontent.com/1479802/152546928-f79cd3a5-a7ff-4f26-9cc4-8cb6d068babd.gif)

2022-02-04 19:57 UTC, mds1 commented
Ah whoops I was looking at the send page, not receive page 🤦

Either way, just pushed a fix—let me know if that works!

2022-02-04 22:07 UTC, apbendi approved these changes
It works! 👍

2022-02-04 22:07 UTC, merged

2022-02-08 06:37 UTC, thelostone-mc commented on frontend/src/components/AccountReceiveTableWithdrawConfirmation.vue
> +          to: toAddress(props.destinationAddress, provider.value),
Oh nice catch here! Derp can't believe i missed that
Sorry about that @apbendi

2022-02-08 06:38 UTC, thelostone-mc commented
Ah thanks for pushing that in @mds1  <3