Enable monorepo to be required as dependency
ScopeLift/umbra-protocol pull request #97
Opened 2021-02-24 20:46 UTC by wildmolasses

This small set of changes enables us to install the monorepo as a dependency of another repo using a git url

2021-03-01 16:44 UTC, apbendi requested changes
Hey @wildmolasses, thanks for this! First request: do you mind squashing all of these down to one commit with a concise explanation?

Also, when I went to run `yarn install` then `yarn test`, I get this error:

```
yarn test
yarn run v1.22.10
$ lerna run test
lerna notice cli v3.22.1
lerna info versioning independent
lerna info Executing command in 3 packages: "yarn run test"
@umbra/contracts: $ concurrently --success first --kill-others "hardhat node &>/dev/null" "hardhat test --network localhost"
@umbra/contracts: [1] Please set your MNEMONIC in a .env file
@umbra/contracts: [1] Please set your INFURA_API_KEY in a .env file
@umbra/contracts: [1] Creating Typechain artifacts in directory typechain for target ethers-v5
@umbra/contracts: [0] hardhat node &>/dev/null exited with code 1
@umbra/contracts: --> Sending SIGTERM to other processes..
@umbra/contracts: [1] hardhat test --network localhost exited with code SIGTERM
@umbra/contracts: error Command failed with exit code 1.
@umbra/contracts: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run test exited 1 in '@umbra/contracts'
error Command failed with exit code 1.
```

2021-03-02 16:27 UTC, apbendi commented
@wildmolasses `contracts/.env` is configured, but still seeing this error:

```
yarn run v1.22.10
$ lerna run test
lerna notice cli v3.22.1
lerna info versioning independent
lerna info Executing command in 3 packages: "yarn run test"
@umbra/contracts: $ concurrently --success first --kill-others "hardhat node &>/dev/null" "hardhat test --network localhost"
@umbra/contracts: [1] Creating Typechain artifacts in directory typechain for target ethers-v5
@umbra/contracts: [0] hardhat node &>/dev/null exited with code 1
@umbra/contracts: --> Sending SIGTERM to other processes..
@umbra/contracts: [1] hardhat test --network localhost exited with code SIGTERM
@umbra/contracts: error Command failed with exit code 1.
@umbra/contracts: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run test exited 1 in '@umbra/contracts'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

2021-03-02 20:52 UTC, wildmolasses commented
Thanks Ben, could you `cd contracts` and run `yarn hardhat node` please? I'm wondering whether there's some port conflict on your machine that doesn't let us stand up a node on port 8545. If so, we could change the local network port.

2021-03-02 21:48 UTC, apbendi commented
> I'm wondering whether there's some port conflict on your machine that doesn't let us stand up a node on port 8545

This was it, @wildmolasses. Sorry 🤦

2021-03-03 03:12 UTC, merged